muscles :
  type: rest
  resource:     "AppBundle:Api\MuscleRest"
  prefix: muscle
  name_prefix:  api_
users :
  type: rest
  resource:     "AppBundle:Api\UserRest"
  prefix: user
  name_prefix:  api_