# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    manager.muscle.class: AppBundle\Manager\MuscleManager

services:
    listener.user.registration:
        class: AppBundle\Listener\PrePersistListener
        arguments: [@security.token_storage]
        tags:
            - { name: 'doctrine_mongodb.odm.event_listener', event: 'prePersist'}

    manager.muscle:
        class: %manager.muscle.class%
        arguments: [@doctrine.odm.mongodb.document_manager]