# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    manager.muscle.class: AppBundle\Manager\MuscleManager

services:
    listener.user.registration:
        class: AppBundle\Listener\PrePersistListener
        arguments: [@security.token_storage]
        tags:
            - { name: 'doctrine_mongodb.odm.event_listener', event: 'prePersist'}

    manager.muscle:
        class: %manager.muscle.class%
        arguments: [@doctrine.odm.mongodb.document_manager]

    form.muscle:
              factory_service: form.factory
              factory_method: createNamed
              class: %symfony.form.class%
              arguments:
                  - muscle
                  - muscle_type

    muscle.form_type:
        class: AppBundle\Form\Type\MuscleType
        tags:
            - { name: form.type, alias: muscle_type}

    handler.muscle:
        class: AppBundle\Form\Handler\MuscleHandler
        arguments: [@form.muscle, @request, @security.token_storage, @manager.muscle]
        scope: request